### ISSUE TITLE
Empty sink when running docker container [Server]: Initialized sinks: [] 

### ISSUE THREAD

**Issue by AminAvanessian** [divolte/docker-divolte#4]
[Server]: Initialized sinks: []

running as docker container, kafka disabled but HDFS enabled

Want to submit events directly to HDFS without using Kafka, works fine in stand-alone app but does not work in docker version of app.

**Comment by AminAvanessian** [comment]
docker-divolte_1  | 2018-08-13 22:55:25.477Z [main] INFO  [Version]: HV000001: Hibernate Validator null
docker-divolte_1  | 2018-08-13 22:55:26.030Z [main] INFO  [SchemaRegistry]: Using builtin default Avro schema.
docker-divolte_1  | 2018-08-13 22:55:26.276Z [main] INFO  [SchemaRegistry]: Loaded schemas used for mappings: [default]
docker-divolte_1  | 2018-08-13 22:55:26.279Z [main] INFO  [SchemaRegistry]: Inferred schemas used for sinks: [divolte]
docker-divolte_1  | 2018-08-13 22:55:26.285Z [main] INFO  [Server]: Initialized sinks: []
docker-divolte_1  | 2018-08-13 22:55:26.304Z [main] INFO  [Mapping]: Using built in default schema mapping.
docker-divolte_1  | 2018-08-13 22:55:26.327Z [main] INFO  [UserAgentParserAndCache]: Using non-updating (resource module based) user agent parser.
docker-divolte_1  | 2018-08-13 22:55:26.789Z [main] INFO  [UserAgentParserAndCache]: User agent parser data version: 20141024-01
docker-divolte_1  | 2018-08-13 22:55:32.298Z [main] INFO  [Slf4jErrorManager]: 0 error(s), 0 warning(s), 87.33860891295294% typed
docker-divolte_1  | 2018-08-13 22:55:32.299Z [main] INFO  [JavaScriptResource]: Pre-compiled JavaScript source: divolte.js
docker-divolte_1  | 2018-08-13 22:55:32.338Z [main] INFO  [GzippableHttpBody]: Compressed resource: 9558 -> 4161
docker-divolte_1  | 2018-08-13 22:55:32.356Z [main] INFO  [BrowserSource]: Registered source[browser] script location: /divolte.js
docker-divolte_1  | 2018-08-13 22:55:32.356Z [main] INFO  [BrowserSource]: Registered source[browser] event handler: /event
docker-divolte_1  | 2018-08-13 22:55:32.356Z [main] INFO  [Server]: Initialized sources: [browser]
docker-divolte_1  | 2018-08-13 22:55:32.379Z [main] INFO  [Server]: Starting server on 0.0.0.0:8290
docker-divolte_1  | 2018-08-13 22:55:32.399Z [main] INFO  [xnio]: XNIO version 3.3.8.Final
docker-divolte_1  | 2018-08-13 22:55:32.415Z [main] INFO  [nio]: XNIO NIO Implementation Version 3.3.8.Final


output^

**Comment by krisgeus** [comment]
Reproducible with the following command:
```
docker run -e "DIVOLTE_KAFKA_ENABLED=false" -e "DIVOLTE_HDFS_ENABLED=true" -p 8290:8290 krisgeus/docker-divolte
```

Will investigate!

**Comment by krisgeus** [comment]
There is no default hdfs sink configured in the divolte-collector.conf. Should be something like this:
```
my_sink = {
      type = hdfs
      file_strategy {
        sync_file_after_records = 1000
        sync_file_after_duration = 30 seconds
        working_dir = /tmp
        publish_dir = /tmp
      }
    }
```

Can add this to the default configuration

**Comment by krisgeus** [comment]
@AminAvanessian Pull request available. Feel free to review and comment.

**Comment by krisgeus** [comment]
https://hub.docker.com/r/divolte/divolte-collector/ has the latest docker container
